### ISSUE TITLE
Drag handle won't work on appended blocks?

### ISSUE THREAD

**Issue by vcordes** [kombai/freewall#137]
Hi,

Following the drag handle example http://vnjs.net/www/project/freewall/example/draggable.html

If a block is appended using the appendBlock method and the added html has a data-handle attribute the entire block will listen for the drag event and act accordingly, as though no handle exists.

Any ideas?

Thank you!

**Comment by kombai** [comment]
Hi,
when you append new blocks, you also set this property: 
data-draggable=true
so the new blocks can be draggable
Best

**Comment by vcordes** [comment]
Thank you for the quick reply!  

That did not appear to work...but I don't think I explained the issue correctly =).  The new blocks were always draggable.  I want to limit drag listeners to the handle section for appended blocks.  Currently, appended blocks will drag anywhere when clicked, even within the designated handle area.

ex: If I pre-populate the wall as per http://vnjs.net/www/project/freewall/example/draggable.html and then instantiate the plugin, the handle area works and limits the drag event listeners to that section of the block div.handle, just like in your example.  However, appended blocks thereafter seem to ignore the drag item handle and behaves as though no handle exists.  Non handle sections are able to drag the block.

Thanks for your time!

**Comment by vcordes** [comment]
Hi again,

Discovered the problem.  It's on my side.  The object was being rendered too late and your awesome plugin couldn't identify the drag element correctly.

Thanks again!
