### ISSUE TITLE
Grid layout-On resize height of the block changing.

### ISSUE THREAD

**Issue by balakrishna-m** [kombai/freewall#140]
I am working on grid lay out.On resizing of the browser I need only the width of the blocks to adjust.Height should remain same.Is there any way I can achieve this ?

**Comment by kombai** [comment]
Only way you can do it by change the Freewall source.
Find the line 394 then change it to:
```js
runtime.cellH = cellH;
```

**Comment by balakrishna-m** [comment]
Great.Now it works as I wanted.
