### ISSUE TITLE
Freewall doesn't load in on first entrance of webpage in Chrome and Safari

### ISSUE THREAD

**Issue by Timme77** [kombai/freewall#147]
Hi,

I have an issue with Freewall on my website. I want to show a flex-grid and it all works fine in FF.
When i try to load the page in Chrome or Safari the grid is not formed by the plugin. If i stay on this page and i refresh it or when i resize it the grid is shown correctly. Any suggestions? This is the code that i'm using. Thanks for your response!

$(document).ready(function() {
	var gutter = 2;
	var wall = new freewall("#block-views-portfolio-block-1 .view-content");
			
	wall.reset({
		selector: '.views-row img',
		animate: true,
		cellW: 150,
		cellH: 'auto',
		gutterX : gutter,
		gutterY: gutter,
		fixSize: 0,
		onResize: function() {
			wall.fitWidth();
		}
	});

	var images = wall.container.find('.views-row');
	images.find('img').load(function() {
		wall.fitWidth();
	});
});

**Comment by daniftinca** [comment]
did you fix it ?  i have a similar problem
