### ISSUE TITLE
Images Layout - keeping the same layout and image sizes

### ISSUE THREAD

**Issue by tsdevteam** [kombai/freewall#154]
Hi,

We are using the images layout and think it's great except when we refresh the page e.g. (http://vnjs.net/www/project/freewall/example/image-layout.html) it changes the layout and image sizes. Is there anyway we can keep the exact same layout every time it refreshes? We need it to be fixed to the same position all the time.

Thanks

**Comment by tsdevteam** [comment]
Hi all, just following up on this if anyone can please help with this question that would be much appreciated. Unfortunately we are on a tight deadline to implement our solution.

Many thanks in advance

**Comment by alexelash** [comment]
Hi. Not sure if this is still relevant to you guys, but I think that this is related to my recent question here: https://github.com/kombai/freewall/issues/184 . It's not how Freewall is really made to work, but the plugin author gave a very helpful solution.

I ended up telling freewall to do the following:
<pre>
wall.reset({
      selector: '.brick',
      animate: true,
})
wall.fitWidth(initialWindowWidth);
</pre>

Then, outside of Freewall's resize function, I added this code:
<pre>
$(window).on("resize", function() {
      var magicNum = $(window).width()/initialWindowWidth;
      $('#freewall-container').css('-webkit-transform', 'scale('+magicNum+')');
});
</pre>

Just make sure that you apply <pre>-webkit-transform-origin: top left;</pre> to your CSS. Hope that this helps!

**Comment by kombai** [comment]
Thank you @alexelash 👍
