### ISSUE TITLE
appendHoles method is not working for me

### ISSUE THREAD

**Issue by aksahyPrabs** [kombai/freewall#164]
GREAT GREAT PLUGIN, thanks for the work.

But currently facing an issue, tried using appendHoles()method using the below code,

socialViz.twitterWall.wall = new freewall("#freewall");
        socialViz.twitterWall.wall.reset({
            selector: '.brick',
            animate: false,
            cellW: 300,
            cellH: 'auto',
            // gutterX: 4,
            // gutterY: 4,
            onResize: function() {
                socialViz.twitterWall.wall.fitWidth();
            }
     });

socialViz.twitterWall.wall.appendHoles({
                    top: 10,
                    left: 36,
                    width: 200,
                    height: 600
                });

**Comment by kombai** [comment]
Hi,
the unit of top/left/with/height used in appendHoles that is "block" unit.
example with your config, we have cell width (cellW) is 300px; and the holes width: 200.
Then the real hole width will be 300 * 200 = 6000px.
So please try :
```js
socialViz.twitterWall.wall.appendHoles({
top: 1,
left: 2,
width: 1,
height: 1
});
``

**Comment by aksahyPrabs** [comment]
Thanks for the prompt response.!!
I did try that, but cant see any empty area in the layout.I even tried calloing refresh method.

I want to create a hole so that I can add custom component on the heart of the pintrest layout.

**Comment by kombai** [comment]
Hi,
You might try to setHoles firtst, then appendHoles later. Please take a look in this page:
https://github.com/kombai/freewall/blob/master/404.html

**Comment by aksahyPrabs** [comment]
Thanks again for the reference...I will play around with this example.!!

**Comment by aksahyPrabs** [comment]
Figured out the problem.
I have cellH: 'auto' in my wall config, because of which the appendHoles in not working.

Once I change the cellH to static value of 300 it works.

Is there a way to get it working with cellH as auto.?

**Comment by kombai** [comment]
You can set cellH small:

cellH: 10,

**Comment by aksahyPrabs** [comment]
Yea..thats what I was trying...that might do the trick...But is there a way to find that empty spot on the wall...How can I get the DOM object of the hole If I want to insert custom HTML there.?

**Comment by kombai** [comment]
The hole it is really the hole :d, so it haven't any object! But you can get the position of the hole, you insert custom HTML then move it to the hole position. 
```js

onComplete: function(item, block, setting) {
  var cellW = setting.runtime.cellW;
  var cellH = setting.runtime.cellH;

  var holdTop = your setting top * cellH;
  var holdLeft = your setting left * cellW;
  
  your custom object.css({top: holdTop, left: holdLeft});
}
```

**Comment by aksahyPrabs** [comment]
yea..that seems to be doable...but still having issues with appendHoles..I need to have the height 'auto' in my wall config as its all dynamic data..If i set it to 10 I get a lot of white space.

**Comment by aksahyPrabs** [comment]
I ended up using appendBlock with data-postion attribute to get onto the center of screen.

Thanks for the reply and help on this.

**Comment by aksahyPrabs** [comment]
So below is the block of code if anyone is looking to dynamically insert custom HTML after the layout is generated.

```javascript
var wall = new freewall(".free-wall");
        wall.reset({
            selector: '.brick',
            animate: false,
            cellW: 300,
            cellH: 'auto',
            fixSize: 0 //Need to add this attribute if you cellH is dynamic
        });
var yourCustomMarkup = '<div class="brick" data-fixSize=true  data-position="650-2" ></div>';
wall.appendBlock(yourCustomMarkup);

**Comment by kombai** [comment]
Thank @aksahyPrabs
