### ISSUE TITLE
Some blocks disappear after certain resolution

### ISSUE THREAD

**Issue by prem11** [kombai/freewall#166]
Hi Minh Nguyen,
Awesome work. 
I have two queries to ask.
1.)At certain resolution (to be exact, at 340px scree width) some of the bigger blocks of size 450px by 450px disappear. Is there a way to make them stay at all resolutions.

 2.)And at resolutions below 335px screen width all the blocks become square. How can i make them stay as a rectangle at all resolutions?

 It is alright if the blocks shrink, but it has to remain a rectangle and do not disappear.

Thanks in advance.

**Comment by pdrazewski** [comment]
Hi!. Same problem here.

**Comment by mnajafzadeh** [comment]
Same problem for me.

**Comment by gnowenegue** [comment]
Same issue for me as well. Please advise soon. Thanks!

**Comment by kombai** [comment]
Hi,
Please using cellW and cellH as a function to have more control.
Check on this issue for the example:
https://github.com/kombai/freewall/issues/212
Best
