### ISSUE TITLE
Freewall doesn't load all my bricks

### ISSUE THREAD

**Issue by ToonMolo** [kombai/freewall#168]
I have a strong problem with Freewall. 

Freewall loads me all the bricks at the first time. When i load the page, Freewall shows me half bricks and the first time, he load nothing.

I don't understand why. Any idea ?

My code 

var wall = new Freewall("#freewall");
    wall.reset({
        selector: '.brick',
        animate: true,
        cellW: function () {
            if (viewport.width > 640) {
                return 330;
            }
        },
        cellH: 'auto',
        gutterY: 2,
        gutterX: 2,
        onResize: function () {
            wall.fitWidth();
        }
    });
    wall.fitWidth();

    var images = wall.container.find('.brick');
    images.find('img').load(function () {
        wall.fitWidth();
    });

**Comment by kombai** [comment]
Hi, do you have a link for check ?

**Comment by ToonMolo** [comment]
Hi !!

You can see here : ftprod.pierrejolly.fr

**Comment by kombai** [comment]
Hi
you are missed this block code:
```js
var images = wall.container.find('.brick');
images.find('img').load(function () {
    wall.fitWidth();
});
```
the images must be loaded to get them size. then Freewall can aranges them.

**Comment by ToonMolo** [comment]
I already try to add this block code (on my local site) and i have the same result

**Comment by kombai** [comment]
Have you try to remove all image, then push some example text instead of image ? Just to see how Freewall work ;)
