### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by therockstar** [kombai/freewall#172]
G'Day,

My developer implemented freewall.js on comment section of product review page. When user click on 'Reply to this comment' button the section of 'Replying comment' is appearing behind the another user comment. 

Please check out the link
http://proof6.hometesterclub.com/au/en/HomeTestedTrial/new-chux-duets/11074

Here is the temp user account.

Email: htctester1@htcseed.com
pass: 12345

and help find some solution of this problem.

Thanks you

**Comment by kombai** [comment]
Fixed by themself
