### ISSUE TITLE
Pass a filter value from one page to another

### ISSUE THREAD

**Issue by Philographie** [kombai/freewall#176]
Hi,
And thanks Kombai for this great plugin ;-)
I use a Freewall on my home page and I wonder how to pass a filter value from an other page to my home. I have an URL with ?param=filter1 and need to filter the wall of my home page with it.
Any idea ?

Thx,
françois

**Comment by kombai** [comment]
Hi,
It is simple. Fist you must get the param value:
http://stackoverflow.com/questions/827368/using-the-get-parameter-of-a-url-in-javascript
Then you init Freewall with value you got:
http://vnjs.net/www/project/freewall/example/demo-filter.html
Best,
Minh

**Comment by Philographie** [comment]
Thx Kombai,
I know how to get the param, but my problem is to initialyse FreWall with the param I got ;-)

**Comment by kombai** [comment]
Here is it:
```js
var wall = new freewall("#freewall");
				wall.reset({
					selector: '.brick',
					animate: true,
					cellW: 160,
					cellH: 160,
					fixSize: 0,
					onResize: function() {
						wall.refresh();
					}
				});
				wall.filter(".size23");
```

**Comment by Philographie** [comment]
Oh yes, so simple... 
Many thx Kombai !
