### ISSUE TITLE
Media query issues

### ISSUE THREAD

**Issue by mophiEU** [kombai/freewall#179]
Hi! 
I've created media queries in CSS to hide certain elements and to increase text size etc. on mobile devices. As I get it to work properly when resizing my browser's window, my iphone won't pick up the media queries. 

Is there a solution for this? Would really appreciate answers!

Thanks

**Comment by mophiEU** [comment]
Solved, if someone else makes this rookie mistake, try including this in your html file:

<meta name="viewport" content="width=device-width, initial-scale=1.0">

**Comment by kombai** [comment]
Thanks mophiEU +1:
