### ISSUE TITLE
Question: fitWidth only once?

### ISSUE THREAD

**Issue by alexelash** [kombai/freewall#184]
Hey, 

First of all: this is a __wonderful__ plugin. My layout calls for 1px gutters and a mosaic of different-sized thumbnails, and I tried many other plugins that left gaps and overlaps, etc before finding yours—THANK YOU. 

Right now I'm using __wall.fitWidth()__ on my grid, and as the client is very specific about the order of thumbnails. I essentially don't want any reordering of my grid items. Is there a way to call the plugin, and then have that grid stay in the same format on resize? 

Wide screens would look like this
![screen shot 2015-08-25 at 10 46 52 am](https://cloud.githubusercontent.com/assets/5672295/9469774/e64241c0-4b16-11e5-887d-de94998f7164.jpg)

and Narrow screens would stay in the same format on resize
![screen shot 2015-08-25 at 10 47 53 am](https://cloud.githubusercontent.com/assets/5672295/9469756/cf9019a2-4b16-11e5-9cc7-0cabe7f9a41c.jpg)

**Comment by kombai** [comment]
Hi, 
You might using keepOrder options:
```js
 wall.reset({
  keepOrder: true,
  ....
 });

```

**Comment by alexelash** [comment]
Thank you for the speedy response! Oddly, that changes the format of the grid entirely, so isn't quite what I'm looking for. It's almost like I just want to freeze the grid as it is (in the format above) and then have it simply get larger and smaller.

![screen shot 2015-08-25 at 11 22 23 am](https://cloud.githubusercontent.com/assets/5672295/9470828/ae621c26-4b1b-11e5-8791-282525773dde.jpg)

**Comment by kombai** [comment]
Hi, it can't resolve by Freewall. But you can using css3 transform scale to get it done.
example you init Freewall with width: 1000px; then you resize to with: 500px;
you just set scale of wall container to 0.5
http://www.w3schools.com/css/css3_2dtransforms.asp
That is it.

**Comment by alexelash** [comment]
Okay! Trying to figure that out now. Thanks for the help, I really appreciate it.
