### ISSUE TITLE
onResize, setbricks to all be the same size when window width is narrow

### ISSUE THREAD

**Issue by alexelash** [kombai/freewall#185]
Hi,

Wondering if this is possible. I have bricks of all different proportions and sizes. On a mobile screen, however, I want these bricks to all stack as perfect squares. Is it possible to force the bricks to take on a square format with Freewall? 

Code:
<pre>
        wall.reset({
			selector: '.grid-item',
			animate: true,
			cellW: 0.25,
			cellH: 0.25,
			gutterX: 1,
	        gutterY: 1,
			onResize: function() {
				wall.fitWidth();
			},
		});
</pre>

Desktop:
![screen shot 2015-08-27 at 10 29 19 am](https://cloud.githubusercontent.com/assets/5672295/9523139/8d7e58bc-4ca6-11e5-9d88-2a23d2fb7306.jpg)

Mobile
![screen shot 2015-08-27 at 10 29 29 am](https://cloud.githubusercontent.com/assets/5672295/9523142/906f8122-4ca6-11e5-9832-b5432410b3ea.jpg)

**Comment by kombai** [comment]
Hi,
Please try with this code:
```js

wall.reset({
            selector: '.grid-item',
            animate: true,
            cellW: function() {
              var width =  $(window).width();
              if (width < 1000) return width;
             else return 0.25;
           },
            cellH:  function() {
              var width =  $(window).width();
              if (width < 1000) return width;
             else return 0.25;
           },
            gutterX: 1,
            gutterY: 1,
            onResize: function() {
               var width =  $(window).width();
               if (width < 1000) {
                   wall.container.find(".brick").css({
                      width: width,
                      height: width
                  })  
              }
                wall.fitWidth();
            },
        });

```js


it not exactly but you can look and modify for fit your issue. The idea is when is it mobile screen. 
You must take the sreen width then set  as width and height for all item.
Best.

**Comment by alexelash** [comment]
Wow. Thank you so much, I wish I had thought of that! It actually is __exactly__ what I was looking for. Really appreciate it! And thanks again for making such a great plugin!
