### ISSUE TITLE
Way to completely destroy freewall function/class?

### ISSUE THREAD

**Issue by gerharddt** [kombai/freewall#186]
My problem is that it loads fine on load and refresh, but the moment I re-size it does it's own thing. I just want it to arrange in the way I set (and it's doing on load/refresh)

So I was thinking that on re-size I can simply destroy it completely and run the whole script again, that should fix it right?

**Comment by abirduphigh** [comment]
Try using: `onResize: null`

```javascript
<script type="text/javascript">

        var wall = new freewall(".free-wall");
        wall.reset({
            onResize: null
        });

</script>
```
