### ISSUE TITLE
How to set up data-wall-width?

### ISSUE THREAD

**Issue by RafaelaCoelho** [kombai/freewall#187]
Hi there,
I am a newbie here and with Freewall.
I want to set up data-wall-width with 1188px. And make it with 4 columns.
Can you halp me and teach me how to do it?

Thank you so much.
Rafaela

**Comment by kombai** [comment]
Hi,
You can try there:
```js
 wall.container.width(1188);
 wall.reset({
 ...
 selector: '.item',
 cellW: 0.25 
 ...
});
```

```css 
.item {
 width: 25%
}
```

**Comment by RafaelaCoelho** [comment]
Thank you so much.
Can you help me and teach where can i put it on freewall.js or index.js?
Thank you

**Comment by kombai** [comment]
You put it in the index.js fille. 
Please see how to using Freewall in the "example" folder.

**Comment by timepp** [comment]
why do we need modify too many parameters to change column width? here you modified 3:
1. the container width
2. the cellW
3. the item width in css

**Comment by kombai** [comment]
@timepp  that for fill all tile in the container. 
Example you have 22 candies, and you have 7 kids, so you can divide for them right ?
So solution is you just eat one candy. So you have 21 candies, then easy for you divide for 7 kids.
Other solution you can buy more 2 candies, so you have 24 candies. And you must find more one kid.
This time you easy to divide 24 candies for 8 kids.
That is it.
