### ISSUE TITLE
Flex layout & overlapping bricks

### ISSUE THREAD

**Issue by Daboloskov** [kombai/freewall#190]
Hi,

The only "no bullshit" plugin so far. But after server upload I encounter some overlapping issues with the bricks. See: http://imgur.com/4wMTsNJ
You can see it live: http://www.organse.com/lookbook

Any ideas on what happened?

Best regards,
Dab

**Comment by Daboloskov** [comment]
Alright so I tried this function to load the picture before the script but it doesn't work either.

		var func = {
			preload: function() {
				var images = []
				for (var i = 1 ; i < 50 ; ++i) {
					images[i] = new Image();
					images[i].src = "<?= TEMPLATE_URL ?>img/lookbook/" + i + ".jpg";
					images[i].onload = function() {
						window["console"] && console.log(this.src);
					}
				}
			}
		}

**Comment by kombai** [comment]
Hi,
You must to let this function do same that:
```js
func.preload();
```

**Comment by piyushcrive** [comment]
Hey, @Daboloskov
Did you find a solution to this? I am facing the same issue. Can you please guide me here?
