### ISSUE TITLE
Items to the right are cut off or extended, resulting in wrong aspect ratio.

### ISSUE THREAD

**Issue by AndersBillLinden** [kombai/freewall#193]
On the site d e n t e m a.s e/bilder2 (remove the spaces), the rightmost divs width are adjusted so they fill out the available space. However, the aspect ratio of them is not the same as the one of the background image. The result will be background images either cut off or repeated.The expected behavior is that the original aspect ratio of a div is kept, possibly scaling a whole row of images to make that happen.

**Comment by AndersBillLinden** [comment]
Also, nothing happends when resizing the window.

**Comment by kombai** [comment]
It cut off because it must to fill all gap. You can try with other setting:
```js
wall.reset({
  ...
  fixSize: 0
  ...
})
```
or 

```js
wall.reset({
  ...
  fixSize: 1
  ...
})
```
but with this setting it not able to fill all gap.
Best
