### ISSUE TITLE
Zoom on Hover

### ISSUE THREAD

**Issue by jdrsqrd** [kombai/freewall#194]
I want to be able to hover the mouse over a block and have it expand in size while the other blocks re arrange around it, then shrink back down when the mouse is moved away. Is this possible?

**Comment by jdrsqrd** [comment]
Any update here?

**Comment by kombai** [comment]
Yes,
You can use fixSize method for change block size when mouse over:
```js
wall.fixSize({
                    height: 5,
                    width: 2,
                    block: $('.free')
                });
```
one think, the number 5 in above example that it is multi time of cellH
