### ISSUE TITLE
freewall not working with ng-repeat

### ISSUE THREAD

**Issue by ravishan110** [kombai/freewall#200]
I have a content array which increases dynamically. I place `md-card` with the content of the elements of that array in a container. For this I am using ng-repeat, but it seems like firewall doesn't work with ng-repeat. If any way exists?

**Comment by debasispanda** [comment]
Hi @ravishan110 ,

1. Try with custom directive for the element where you using the freewall and initialize the freewall plugin after all the elements are rendered. i.e Just after the ng-repeat completes the loop. 
2. You can also use $timeout and then initialize the freewall. But i will recommend the first option.

Hope this will solve your issue.

**Comment by dragonfish-au** [comment]
When you have a large list to render, ng-repeat is very slow.
My approach is
# generate the html for the dynamically inserted items
# use wall.appendBlock(html) to insert the html

sample: https://collector.im/

**Comment by kombai** [comment]
Thank @debasispanda  and @dragonfish-au
