### ISSUE TITLE
Freewall will fire until window is resized

### ISSUE THREAD

**Issue by lr150561** [kombai/freewall#203]
Hello, 

I am loving Freewall but am having a hard time getting it to fire on page load. I am getting the images using instafeed.js. No matter how far down I put the script or even if I tell it to execute after all images are loaded it will not until I resize the browser. Any help would be hugely appreciated..

Thanks!

**Comment by daniftinca** [comment]
i have this problem too. 
On my page I have two freewall galleries. The first one loads without a problem but the second one loads with images of random width and height, but returns to normal on resize or even if i click on inspect element. (i tested in mozilla)

**Comment by m3xx** [comment]
i have this problem too.

**Comment by tiersept** [comment]
I'm guessing all of you are using the Pinterest grid?

**Comment by tiersept** [comment]
try this under your freewall script

$(window).trigger('resize');

**Comment by dragonfish-au** [comment]
Hi @lr150561 

I believe you didn't do it write. I trigger wall.refresh() after all images being loaded (exclude those image loading errors).

sample code like this

``` 
var images = $(html).find('img');
var length = images.length;
images.load(checkImageStatus);
images.error(checkImageStatus);

wall.appendBlock(html);

function checkImageStatus() {
    --length;
    if (!length) {
        setTimeout(function () {
            wall.refresh();
        }, 505);
    }
}
```

**Comment by kombai** [comment]
Thank you @dragonfish-au  👍 

https://github.com/kombai/freewall/issues/203
https://github.com/kombai/freewall/issues/207
https://github.com/kombai/freewall/issues/208
