### ISSUE TITLE
Freewall only works when I resize the window (in combination with popup)

### ISSUE THREAD

**Issue by TekniC88** [kombai/freewall#207]
Dear,

I have a one page website http://ontwerp.kmosites.be/work-2016/f/fameworks/www/
When you click on cases and afterwards on the first case "Dovre", this uses a jquery Magnific popup.js to show text and images (wrapped in freewall)
But the freewall only works when I resize the window, not when the popup opens.
Could you please help?

Thanks,
Nicolas

**Comment by dragonfish-au** [comment]
See answer on issue #208
