### ISSUE TITLE
Featured Block working fine but  For Specific Window Width Its not working .

### ISSUE THREAD

**Issue by asifali1** [kombai/freewall#213]
Hi A gret plugin.
one issu if you can help.
My code works fine other screen sizes but on screen size between 585px to 615px on chrome its not getting the width of my featured block. At this screen size its rendering it as normal block . 
i am just having problem at this screen size else its getting my featured block width as 414 px .
Is there a way i can just implement the plugin to get this featured block width on this screen size too.please guide how to write this in your plugin
Thanks alot 
like this 

If (screen size is in between 585 to 615 ){
featured block width = 414;
} 
my code is as below
var wall = new Freewall('.free-wall');
var featured= $(".free-wall .featured");
wall.reset({
                selector: '.brick',
                animate: true,
                cellW: 200,
                cellH: 'auto',
                onResize: function() {
                    
                      wall.fixSize({
                      block: featured,
                      width: 414,
                      height: auto
                     });
                    wall.fitWidth();
                }
 wall.fixSize({
                      block: featured,
                      width: 414,
                      height: auto
                     });
wall.fitWidth();

**Comment by kombai** [comment]
Hi,
You can using cellW as a function for this feature. Please take a look on this issue:
https://github.com/kombai/freewall/issues/212
