### ISSUE TITLE
Pinterest grid strange behaviour

### ISSUE THREAD

**Issue by tiersept** [kombai/freewall#215]
Hey,

I don't know if anyone has noticed or it only happens to me but the Pinterest example grid sometimes loads weirdly in Google Chrome when referred to through a link. 

http://vnjs.net/www/project/freewall/example/pinterest-layout.html

Looks like this:

![pinterest first load](https://cloud.githubusercontent.com/assets/18143464/14109146/04bdaefa-f5c1-11e5-8fa7-ae73bd1403de.jpg)

As you can see, the grid is pushed to the left and sits weird. However when the window is resized, everything pops in place.

On my own website, I have applied the same code from this Pinterest grid and I am noticing some strange behaviour too when the page initially loads. This happens randomly, sometimes the grid renders fine, sometimes it does not.

Weird:

![website](https://cloud.githubusercontent.com/assets/18143464/14109241/53c812f6-f5c1-11e5-8804-d562e43a163b.png)

Good:

![website good](https://cloud.githubusercontent.com/assets/18143464/14109249/5ca3d504-f5c1-11e5-8ca9-7ff11e22270a.png)

I have added a script to force a second page reload when the page loads which should not be needed right? This however does makes sure the Freewall script fires but it does not always fix the problem. Resizing the window does not render the lost images and solve the issue.

Any ideas fellas? Thanks!

**Comment by kombai** [comment]
Hi,
The problem because the iamge not loaded yet. You can see on this issue to reslove it:
https://github.com/kombai/freewall/issues/208
