### ISSUE TITLE
Freewall- Using "or" on filters when multiple filters are used

### ISSUE THREAD

**Issue by annatrivino** [kombai/freewall#218]
Hello!

I observed that when I use multiple filters, that OR is applied to the filters.  I need to filter using and AND operator.  Is this something that can be passed as a parameter?

Please help.

Thanks so much in advance!

**Comment by kombai** [comment]
Hi,
Freewall used the jQuery filter, so I think you can try with this:

http://stackoverflow.com/questions/10687131/jquery-select-by-attribute-using-and-and-or-operators
 
Hope it help you well

**Comment by annatrivino** [comment]
Thanks kombai!  The link was very helpful!
