### ISSUE TITLE
Webpage is blank after adding freewall

### ISSUE THREAD

**Issue by Devon-Britton** [kombai/freewall#84]
Hi there.

I'm having an issue implementing Freewall in my website. In desperation I ended up removing most of my own code and copying your example from the website in order to try get it to work but I'm still not having any luck.

The page is completely blank. There are no errors in the javascript console and I really have no idea what might be going wrong.

I tried posting my code but it isn't working for some reason. If anyone wants it I'm happy to send it to them.

This is quite urgent and any help would be greatly appreciated.

Regards, Devon Britton.

**Comment by tomgrandson** [comment]
try to link jqery before freewall.js ;)
