### ISSUE TITLE
Handle block resizing when filling gap

### ISSUE THREAD

**Issue by rapidfixer** [kombai/freewall#99]
I use Freewall with parameter fixSize setted to null, by default.
Blocks in my grid have inner contents of different size - some are very large, and sometimes block with big image and large amount of content (5x1 places, for example) gets resized to fill in 1x1 place. 
Can i somehow handle event of block resizing, to change its inner content to get proper look?
Can i at least change its class on resize?

**Comment by roobeen** [comment]
hey, 

First of all awesome plugin. 
Second m facing an issue with re-sizing.
I am appending data to grid and the grid is coming fine but when i resize window only the preloaded grid gets resized. and the new grid remains the same
![screenshot from 2016-05-12 04 14 34](https://cloud.githubusercontent.com/assets/19315597/15198994/b35da3a8-17f8-11e6-8b5d-53505668170e.png)
.
